### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by zuurw** [saltfish666/pageNote-vue#1]
Good day @saltfish666   I am a graphics designer and open source contributor. I want to contribute to your good project by proposing a logo design for the project which i will be doing for free as a gift. If you will give me permission i will start as soon as possible. Thanks and best regards!

Best Regards

ZW

**Comment by saltfish666** [comment]
Yeah, you're welcome. I am just a programmer which doesn't have any art cells, so I just found some free icons on the iconfinder. It's my pleasure to receive your pull request at any time. Feel free to join this open project.

@zuurw

**Comment by zuurw** [comment]
Hi @saltfish666  i, I will start today working in your logo, do you have any request for the logo, like colors or something more specific? can you say something for inspiration?

Greetings.

**Comment by saltfish666** [comment]
hello @zuurw: 
Sorry to reply to you now (I didn't notice the github notification).
This project is an extension for chrome that helps users take notes on any web page.
So how about drawing a pencil that taking notes?
Or a notebook on a webpage (no idea about painting a `webpage`)?
The only request is chrome requires 128 * 128 pix for the icon.

**Comment by zuurw** [comment]
Hello @saltfish666,
I will design something like what you ask.

Greetings!

**Comment by zuurw** [comment]
Hello @saltfish666 
I create this design for your logo, the concept It´s a pencil where the body of the pencil it´s a note.
I think it looks good, but I will wait for your feedback.

If you want you can choose other colors.

Greetings!
![pagenote proposal](https://user-images.githubusercontent.com/40801473/42464601-787b9a80-83a1-11e8-8fb3-88a5d1eaa8f0.png)

**Comment by saltfish666** [comment]
hi,@zuurw
An amazing job! It looks great to me.

 I just invite you to be [a collaborator of this reposity by click this link](https://github.com/saltfish666/pageNote-Chrome-vue/invitations), which can reduce the cost of communication between each other.

Now you can merge you works by youself. 
You can add icons to `./Chrome-extension/icons/`. Once you done, I will add them to Chrome Store and every user will use you artwork.

By the way, how do you think about make the pen tilt a little more? Well, just say it casually, you decide.

**Comment by zuurw** [comment]
I can do that, I did not because almost all logos with pens and pencils are inclined, so I decided to do so to be different from all of them. But if you want, I will do it.

**Comment by zuurw** [comment]
I made the changes and I tilt the pencil to right and to left, see what you like more, if you want I can send you all the versions, so that you can used how ever you want.

![pagenote proposal2](https://user-images.githubusercontent.com/40801473/42502139-2d10b058-842d-11e8-9731-3df78922ef6b.png)

**Comment by saltfish666** [comment]
You are awesome!

you can make a folder and put all the visions in it.

Then you can make a pull request or merge it yourself.

Once you down, I will let every icon has its own place in Chrome or Application or README. 

@zuurw

**Comment by saltfish666** [comment]
hello @zuurw, how is going

**Comment by zuurw** [comment]
Hello @saltfish666, I create the PR with the logo and add the logo to the README.md.

Do you have more things to do, that I can help?

I saw that you have more projects on Github like: 

- nclone
- serverhere
- rabbit666
- nginx

So if you need logo for them just say it, it will be a pleasure to work in this projects too.

Greetings!

**Comment by saltfish666** [comment]
It's awesome! You icons make this application pretty.

I think `nclone` it a nice cli for developers to build their project, but nobody noticed it.
If you join it, it's highly inspiring for me to maintain and update it.
For more detail, how about open an issue on `nclone` to discuss?

@zuurw

**Comment by saltfish666** [comment]
Hi @zuurw , I hava an other project name [pageNote-web](https://github.com/saltfish666/pageNote-web). It is brother of this repo and it also is MIT license.
Can I reuse you icons in this project?

**Comment by zuurw** [comment]
Hi @saltfish666, sure you can reuse the logo in that project too.
